/**
 * Sparkyservice API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChangePasswordDto } from './changePasswordDto';
import { SettingsDto } from './settingsDto';

export interface UserDto { 
    username: string;
    fullName?: string;
    realm: UserDto.RealmEnum;
    passwordDto?: ChangePasswordDto;
    settings: SettingsDto;
    role?: UserDto.RoleEnum;
    expirationDate?: string;
}
export namespace UserDto {
    export type RealmEnum = 'LOCAL' | 'LDAP' | 'MEMORY' | 'UNKNOWN';
    export const RealmEnum = {
        LOCAL: 'LOCAL' as RealmEnum,
        LDAP: 'LDAP' as RealmEnum,
        MEMORY: 'MEMORY' as RealmEnum,
        UNKNOWN: 'UNKNOWN' as RealmEnum
    };
    export type RoleEnum = 'DEFAULT' | 'ADMIN' | 'SERVICE';
    export const RoleEnum = {
        DEFAULT: 'DEFAULT' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum,
        SERVICE: 'SERVICE' as RoleEnum
    };
}