/**
 * Sparkyservice API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChangePasswordDto } from './changePasswordDto';
import { SettingsDto } from './settingsDto';

export interface UserDto { 
    username: string;
    realm: UserDto.RealmEnum;
    passwordDto?: ChangePasswordDto;
    settings: SettingsDto;
    role?: UserDto.RoleEnum;
}
export namespace UserDto {
    export type RealmEnum = 'LOCAL' | 'LDAP' | 'MEMORY' | 'UNKNOWN';
    export const RealmEnum = {
        LOCAL: 'LOCAL' as RealmEnum,
        LDAP: 'LDAP' as RealmEnum,
        MEMORY: 'MEMORY' as RealmEnum,
        UNKNOWN: 'UNKNOWN' as RealmEnum
    };
    export type RoleEnum = 'DEFAULT' | 'ADMIN';
    export const RoleEnum = {
        DEFAULT: 'DEFAULT' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum
    };
}