/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API description.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupDto } from './groupDto';

export interface AssessmentDto { 
    id?: string;
    assignmentId: string;
    achievedPoints: number;
    comment?: string;
    groupId?: string;
    group?: GroupDto;
    userId?: string;
}