/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API description.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AssignmentDto { 
    id?: string;
    courseId: string;
    name: string;
    state: AssignmentDto.StateEnum;
    startDate?: Date;
    endDate?: Date;
    type: AssignmentDto.TypeEnum;
    maxPoints: number;
    comment?: string;
    link?: string;
}
export namespace AssignmentDto {
    export type StateEnum = 'INVISIBLE' | 'CLOSED' | 'IN_PROGRESS' | 'IN_REVIEW' | 'EVALUATED';
    export const StateEnum = {
        INVISIBLE: 'INVISIBLE' as StateEnum,
        CLOSED: 'CLOSED' as StateEnum,
        INPROGRESS: 'IN_PROGRESS' as StateEnum,
        INREVIEW: 'IN_REVIEW' as StateEnum,
        EVALUATED: 'EVALUATED' as StateEnum
    };
    export type TypeEnum = 'HOMEWORK' | 'TESTAT' | 'SEMINAR' | 'PROJECT' | 'OTHER';
    export const TypeEnum = {
        HOMEWORK: 'HOMEWORK' as TypeEnum,
        TESTAT: 'TESTAT' as TypeEnum,
        SEMINAR: 'SEMINAR' as TypeEnum,
        PROJECT: 'PROJECT' as TypeEnum,
        OTHER: 'OTHER' as TypeEnum
    };
}