/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API description.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CourseDto } from './courseDto';
import { UserDto } from './userDto';

export interface GroupDto { 
    id?: string;
    courseId: string;
    name: string;
    password?: string;
    isClosed?: boolean;
    course?: CourseDto;
    users?: Array<UserDto>;
}