export * from './assessments.service';
import { AssessmentsService } from './assessments.service';
export * from './assignments.service';
import { AssignmentsService } from './assignments.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './courses.service';
import { CoursesService } from './courses.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './mail.service';
import { MailService } from './mail.service';
export * from './test.service';
import { TestService } from './test.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AssessmentsService, AssignmentsService, AuthenticationService, CoursesService, DefaultService, GroupsService, MailService, TestService, UsersService];
