export * from './admissionStatus.service';
import { AdmissionStatusService } from './admissionStatus.service';
export * from './assessmentAllocation.service';
import { AssessmentAllocationService } from './assessmentAllocation.service';
export * from './assessments.service';
import { AssessmentsService } from './assessments.service';
export * from './assignmentRegistration.service';
import { AssignmentRegistrationService } from './assignmentRegistration.service';
export * from './assignments.service';
import { AssignmentsService } from './assignments.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './courseConfig.service';
import { CourseConfigService } from './courseConfig.service';
export * from './courseParticipants.service';
import { CourseParticipantsService } from './courseParticipants.service';
export * from './courses.service';
import { CoursesService } from './courses.service';
export * from './csv.service';
import { CsvService } from './csv.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './mail.service';
import { MailService } from './mail.service';
export * from './taskScheduler.service';
import { TaskSchedulerService } from './taskScheduler.service';
export * from './test.service';
import { TestService } from './test.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AdmissionStatusService, AssessmentAllocationService, AssessmentsService, AssignmentRegistrationService, AssignmentsService, AuthenticationService, CourseConfigService, CourseParticipantsService, CoursesService, CsvService, DefaultService, GroupsService, MailService, TaskSchedulerService, TestService, UsersService];
