/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParticipantDto } from './participantDto';
import { RuleCheckResult } from './ruleCheckResult';

export interface AdmissionStatusDto { 
    hasAdmission: boolean;
    hasAdmissionFromPreviousSemester: boolean;
    fulfillsAdmissionCriteria: boolean;
    results: Array<RuleCheckResult>;
    participant: ParticipantDto;
}