/**
 * Student-Management-System-API
 * The Student-Management-System-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssignmentDto } from './assignmentDto';
import { GroupDto } from './groupDto';
import { PartialAssessmentDto } from './partialAssessmentDto';
import { ParticipantDto } from './participantDto';
import { UserDto } from './userDto';

export interface AssessmentDto { 
    /**
     * Unique identifier of this assessment.
     */
    id?: string;
    /**
     * Identifier of the assignment that is being evaluated by this assessment.
     */
    assignmentId: string;
    /**
     * Marks the assessment as a draft.
     */
    isDraft: boolean;
    /**
     * The amount of points that the student or group achieved with their submission.
     */
    achievedPoints?: number;
    /**
     * A comment providing additional feedback.
     */
    comment?: string;
    /**
     * If a group submission is being evaluated, contains the identifier of the group.
     */
    groupId?: string;
    /**
     * If a single user is being evaluated, contains the identifier of the user.
     */
    userId?: string;
    /**
     * Identifier of the creator of this assessment.
     */
    creatorId?: string;
    /**
     * Identifier of the last user that updated this assessment.
     */
    lastUpdatedById?: string;
    assignment?: AssignmentDto;
    /**
     * The group, whose submission was evaluated by this assessment.
     */
    group?: GroupDto;
    /**
     * If assessment targets a single user, contains the user.
     */
    participant?: ParticipantDto;
    /**
     * The creator of this assessment.
     */
    creator?: UserDto;
    lastUpdatedBy?: UserDto;
    creationDate?: Date;
    updateDate?: Date;
    partialAssessments?: Array<PartialAssessmentDto>;
}