/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CanJoinCourseDto { 
    /**
     * Indicates, wether the joining the course is possible.
     */
    canJoin: boolean;
    /**
     * Indicates, wether the joining the course requires a password.
     */
    requiresPassword?: boolean;
    /**
     * The reason why joining the course is not possible.
     */
    reason?: CanJoinCourseDto.ReasonEnum;
}
export namespace CanJoinCourseDto {
    export type ReasonEnum = 'CLOSED' | 'IS_MEMBER';
    export const ReasonEnum = {
        CLOSED: 'CLOSED' as ReasonEnum,
        ISMEMBER: 'IS_MEMBER' as ReasonEnum
    };
}