/**
 * Student-Management-System-API
 * The Student-Management-System-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ChangeCourseRoleDto { 
    role: ChangeCourseRoleDto.RoleEnum;
}
export namespace ChangeCourseRoleDto {
    export type RoleEnum = 'LECTURER' | 'TUTOR' | 'STUDENT';
    export const RoleEnum = {
        LECTURER: 'LECTURER' as RoleEnum,
        TUTOR: 'TUTOR' as RoleEnum,
        STUDENT: 'STUDENT' as RoleEnum
    };
}