/**
 * Student-Management-System-API
 * The Student-Management-System-API. <a href=\'http://localhost:3000/api-json\'>JSON</a>
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupSettingsDto } from './groupSettingsDto';
import { LinkDto } from './linkDto';
import { AdmissionCriteriaDto } from './admissionCriteriaDto';


export interface CourseDto { 
    /**
     * Unique identifier of this course.
     */
    id?: string;
    /**
     * Shortname of this course, i.e \"java\". Should be reused every semester. Will be used in URLs.
     */
    shortname: string;
    /**
     * Semester that the iteration of this course belong to.
     */
    semester: string;
    /**
     * The full title of this course, i.e Programming I: Java
     */
    title: string;
    /**
     * Determines, wether changes (i.e joining this course) can be made to this course.
     */
    isClosed: boolean;
    links?: Array<LinkDto>;
    groupSettings?: GroupSettingsDto;
    admissionCriteria?: AdmissionCriteriaDto;
}

