/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GroupCreateBulkDto { 
    /**
     * List of group names.
     */
    names?: Array<string>;
    /**
     * If utilized, all group names will use the nameSchema followed by the group's number.
     */
    nameSchema?: string;
    /**
     * The number of groups that should be created. Should only be used in conjunction with nameSchema.
     */
    count?: number;
}