/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MarkerDto { 
    path: string;
    startLineNumber: number;
    endLineNumber: number;
    startColumn?: number;
    endColumn?: number;
    severity: MarkerDto.SeverityEnum;
    comment: string;
    points?: number;
}
export namespace MarkerDto {
    export type SeverityEnum = 'INFO' | 'HINT' | 'WARNING' | 'ERROR';
    export const SeverityEnum = {
        INFO: 'INFO' as SeverityEnum,
        HINT: 'HINT' as SeverityEnum,
        WARNING: 'WARNING' as SeverityEnum,
        ERROR: 'ERROR' as SeverityEnum
    };
}