/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Name = 'CourseClosedException' | 'NotACourseMemberException' | 'GroupsForbiddenException';

export const Name = {
    CourseClosedException: 'CourseClosedException' as Name,
    NotACourseMemberException: 'NotACourseMemberException' as Name,
    GroupsForbiddenException: 'GroupsForbiddenException' as Name
};