/**
 * Student-Management-System-API
 * The Student-Management-System-API. <a href=\'http://localhost:3000/api-json\'>JSON</a>
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationDto { 
    event: NotificationDto.EventEnum;
    courseId: string;
    assignmentId?: string;
    groupId?: string;
    userId?: string;
    payload?: any;
}
export namespace NotificationDto {
    export type EventEnum = 'COURSE_JOINED' | 'ASSIGNMENT_CREATED' | 'ASSIGNMENT_REMOVED' | 'ASSIGNMENT_STATE_CHANGED' | 'GROUP_REGISTERED' | 'GROUP_UNREGISTERED' | 'USER_REGISTERED' | 'USER_UNREGISTERED' | 'USER_JOINED_GROUP' | 'USER_LEFT_GROUP' | 'REGISTRATIONS_CREATED' | 'REGISTRATIONS_REMOVED';
    export const EventEnum = {
        COURSE_JOINED: 'COURSE_JOINED' as EventEnum,
        ASSIGNMENT_CREATED: 'ASSIGNMENT_CREATED' as EventEnum,
        ASSIGNMENT_REMOVED: 'ASSIGNMENT_REMOVED' as EventEnum,
        ASSIGNMENT_STATE_CHANGED: 'ASSIGNMENT_STATE_CHANGED' as EventEnum,
        GROUP_REGISTERED: 'GROUP_REGISTERED' as EventEnum,
        GROUP_UNREGISTERED: 'GROUP_UNREGISTERED' as EventEnum,
        USER_REGISTERED: 'USER_REGISTERED' as EventEnum,
        USER_UNREGISTERED: 'USER_UNREGISTERED' as EventEnum,
        USER_JOINED_GROUP: 'USER_JOINED_GROUP' as EventEnum,
        USER_LEFT_GROUP: 'USER_LEFT_GROUP' as EventEnum,
        REGISTRATIONS_CREATED: 'REGISTRATIONS_CREATED' as EventEnum,
        REGISTRATIONS_REMOVED: 'REGISTRATIONS_REMOVED' as EventEnum
    };
}


