/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RoundingBehavior { 
    type: RoundingBehavior.TypeEnum;
    decimals?: number;
}
export namespace RoundingBehavior {
    export type TypeEnum = 'NONE' | 'DECIMALS' | 'DOWN_NEAREST_INTEGER' | 'UP_NEAREST_INTEGER';
    export const TypeEnum = {
        NONE: 'NONE' as TypeEnum,
        DECIMALS: 'DECIMALS' as TypeEnum,
        DOWNNEARESTINTEGER: 'DOWN_NEAREST_INTEGER' as TypeEnum,
        UPNEARESTINTEGER: 'UP_NEAREST_INTEGER' as TypeEnum
    };
}