/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Rule { 
    /**
     * Determines, wether the rule should be evaluated for every assignment or the summarized points.
     */
    scope: Rule.ScopeEnum;
    /**
     * The assignment type that the rule applies to.
     */
    type: Rule.TypeEnum;
    /**
     * The required percentage to fulfill the rule.
     */
    requiredPercent: number;
}
export namespace Rule {
    export type ScopeEnum = 'OVERALL' | 'INDIVIDUAL';
    export const ScopeEnum = {
        OVERALL: 'OVERALL' as ScopeEnum,
        INDIVIDUAL: 'INDIVIDUAL' as ScopeEnum
    };
    export type TypeEnum = 'HOMEWORK' | 'TESTAT' | 'SEMINAR' | 'PROJECT' | 'OTHER';
    export const TypeEnum = {
        HOMEWORK: 'HOMEWORK' as TypeEnum,
        TESTAT: 'TESTAT' as TypeEnum,
        SEMINAR: 'SEMINAR' as TypeEnum,
        PROJECT: 'PROJECT' as TypeEnum,
        OTHER: 'OTHER' as TypeEnum
    };
}