/**
 * Student-Management-System-API
 * The Student-Management-Sytem-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateMessage { 
    /**
     * The type of event, i.e INSERT, UPDATE or REMOVE.
     */
    type: UpdateMessage.TypeEnum;
    /**
     * The type of object that has been affected.
     */
    affectedObject: UpdateMessage.AffectedObjectEnum;
    /**
     * Identifier of the course, in which the event happened.
     */
    courseId: string;
    /**
     * Identifier of the entity that has changed. Type is always indicated by the first noun of affectedObject.
     */
    entityId: string;
    /**
     * Identifier of the related entity that has changed. Type is always the second noun of affectedObject.
     */
    entityIdRelation?: string;
    /**
     * Timestamp of the event.
     */
    date?: Date;
}
export namespace UpdateMessage {
    export type TypeEnum = 'INSERT' | 'UPDATE' | 'REMOVE';
    export const TypeEnum = {
        INSERT: 'INSERT' as TypeEnum,
        UPDATE: 'UPDATE' as TypeEnum,
        REMOVE: 'REMOVE' as TypeEnum
    };
    export type AffectedObjectEnum = 'USER' | 'GROUP' | 'USER_GROUP_RELATION' | 'COURSE_USER_RELATION' | 'ASSIGNMENT';
    export const AffectedObjectEnum = {
        USER: 'USER' as AffectedObjectEnum,
        GROUP: 'GROUP' as AffectedObjectEnum,
        USERGROUPRELATION: 'USER_GROUP_RELATION' as AffectedObjectEnum,
        COURSEUSERRELATION: 'COURSE_USER_RELATION' as AffectedObjectEnum,
        ASSIGNMENT: 'ASSIGNMENT' as AffectedObjectEnum
    };
}