/**
 * Student-Management-System-API
 * The Student-Management-System-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserSettingsDto { 
    language: UserSettingsDto.LanguageEnum;
    allowEmails: boolean;
    blacklistedEvents?: any;
}
export namespace UserSettingsDto {
    export type LanguageEnum = 'EN' | 'DE';
    export const LanguageEnum = {
        EN: 'EN' as LanguageEnum,
        DE: 'DE' as LanguageEnum
    };
}